[workspace]
authors = ["softwareentrepreneer <softwareentrepreneer+pfund-kit@gmail.com>"]
channels = ["conda-forge"]
name = "pfund-kit"
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]
# NOTE: this depends on the lock version used in setup-pixi in ci.yml
requires-pixi = "<=0.72.2"  # command: pixi workspace requires-pixi set "<=0.72.2"

[tasks]

[tasks.test-all]
depends-on = [
  { task = "test", environment = "py311" },
  { task = "test", environment = "py312" },
  { task = "test", environment = "py313" },
]

[dependencies]

[pypi-dependencies]
rich = ">=13.7.1"
tqdm = ">=4.66.2"
click = ">=8.1.7"
trogon = ">=0.6.0"
pyyaml = ">=6.0.2"
tomlkit = ">=0.15.0"
packaging = ">=24.2"
# platformdirs = ">=4.3.6"
python-dotenv = ">=1.2.2"
prompt-toolkit = ">=3.0.43"

[environments]
default = ["py311", "dev", "optional"]
py311 = ["py311", "test", "optional"]
py312 = ["py312", "test", "optional"]
py313 = ["py313", "test", "optional"]

[feature.optional.pypi-dependencies]

[feature.dev.pypi-dependencies]
pfund-kit = { path = ".", editable = true }
afterpython = ">=0.3.16"

[feature.test.pypi-dependencies]
pfund-kit = { path = ".", editable = true }
pytest = ">=9.0.2"
pytest-cov = ">=7.0.0"
pytest-mock = ">=3.15.1"
pytest-xdist = ">=3.8.0"
[feature.test.tasks]
test = "pytest -n auto"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"
